name: pxc

update:
  canaries: 1
  canary_watch_time: 10000-600000
  update_watch_time: 10000-600000
  max_in_flight: 1
  serial: true

instance_groups:
- name: mysql
  instances: 1
  azs: [z1]
  networks: [{name: default}]
  vm_type: default
  stemcell: default
  persistent_disk: 10000
  jobs:
  - name: mysql
    release: pxc

properties:
  admin_password: REPLACE-ME
  broker_admin_password: REPLACE-BROKER-ADMIN-PASSWORD
  default_schema: default_schema
  mysql_backup_password: REPLACE-BACKUP-PASSWORD

releases:
- name: pxc
  version: latest
stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest
